### ISSUE TITLE
请问，Toast.info()和useToast().info()两种方式有啥区别？

### ISSUE THREAD

**Issue by danna88** [listenzz/react-native-toast-hybrid#11]
如题。。。

另外，duration等配置是全局的吗？ 配置一次，所有使用的地方都生效？

谢谢。

**Comment by listenzz** [comment]
Toast.info() 是一次性的，可以同时存在多个。譬如短时间内调用 Toast.info() 多次，会有多个 toast 重叠在一起。

useToast().info() 只可以在函数组件中使用，是可以复用的，后面的内容会覆盖前面的。譬如

```js

const toast = useToast()

toast.loading('正在加载')

setTimeout(() => {
  toast.done('加载成功')
}, 1000)

```

会先显示 loading, 过一秒后显示 ‘加载成功’ 的提示，然后经过 duration 的时间自动消失。

useToast 还会响应 Android 的返回按钮，当用户按下返回按钮时，toast 会消失。

useToast 会随着页面的销毁而销毁，而 Toast.info() 则会持续到 duration 的时间结束

duration 是全局的，配置一次，所有地方生效。

此外，可以通过 Toast.info('', 3000) 或 useToast().info('', 3000) 来覆盖全局的配置

**Comment by danna88** [comment]
哦~明白了！感谢回答，看着useToast应用场景更多些…

**Comment by danna88** [comment]
还有个问题，我页面大多数是class，所以不能用useToast，我就用的Toast，但是我发现Toast.loading()不能关闭？Toast.hide()没用。。。

**Comment by listenzz** [comment]
const toast = Toast.loading()

toast.hide()

**Comment by listenzz** [comment]
可以考虑写个 HOC

**Comment by danna88** [comment]
嗯嗯，我把它放到自己的一个页面中，忘了写个return

**Comment by danna88** [comment]
嗯嗯，我先简单着来。刚才那个问题是因为，我把它放到自己的一个页面中，忘了写个return
![微信截图_20200430104035](https://user-images.githubusercontent.com/6461710/80666545-1f869b00-8acf-11ea-8515-3be8a9080896.png)

**Comment by listenzz** [comment]
像下面这样写个 HOC，把 useToast 包裹在里面，就可以和类组件一起使用了。

```js
// withToast.js
import React from 'react'
import { useToast } from 'react-native-toast-hybrid'

export default function withToast(WrappedComponent) {
  function ToastH(props, ref) {
    const toast = useToast()
    return <WrappedComponent {...props} toast={toast} ref={ref} />
  }
  const FC = React.forwardRef(ToastH)
  const name = WrappedComponent.displayName || WrappedComponent.name
  FC.displayName = `withToast(${name})`
  FC.navigationItem = WrappedComponent.navigationItem || {}
  return FC
}
```

开始注册页面时，注入 HOC

```js
import { ReactRegistry } from 'react-native-navigation-hybrid'
import withToast from './withToast'

ReactRegistry.startRegisterComponent(withToast)
```

在页面中使用

```js
class Page extends React.Component {
  
  handleSomething = () => {
    this.props.toast.loading('')
  }
}

```

**Comment by danna88** [comment]
学到了！！

**Comment by danna88** [comment]
我是这样合并到我的HOC中的，页面正常，这样没问题吧？ 
function withRedux(WrappedComponent) {
  function ToastH(props, ref) {
    const toast = useToast();
    return <WrappedComponent {...props} toast={toast} ref={ref}/>;
  }

  return props => (
    <Provider store={store}>
      <PersistGate loading={null} persistor={persistenceStore}>
        <ThemeProvider theme={Theme}>
          {ToastH(props)}
        </ThemeProvider>
      </PersistGate>
    </Provider>
  );
}
