### ISSUE TITLE
请问该库支持Expo项目吗？

### ISSUE THREAD

**Issue by likeSo** [listenzz/react-native-toast-hybrid#19]
我看Readme里面直接useToast就可以使用了，我在使用的时候报错说`[Unhandled promise rejection: TypeError: null is not an object (evaluating 'ToastHybrid.config')]
`
我尝试先调用Toast.config也是一样的结果，是因为这个库不支持Expo项目吗？我的项目是Expo Bare Workflow

**Comment by listenzz** [comment]
@likeSo 本库涉及原生代码。你需要了解 expo 是否支持带有原生代码的组件库，如果支持，需要如何配置。

**Comment by likeSo** [comment]
> @likeSo 本库涉及原生代码。你需要了解 expo 是否支持带有原生代码的组件库，如果支持，需要如何配置。

正好这两天Expo更新了，应该是支持了，只需要使用custom-dev-client编译出来一个独立的app即可。
