### ISSUE TITLE
安装@heytea/react-native-heytea-qrcode库后ios编译失败

### ISSUE THREAD

**Issue by baiachen** [listenzz/react-native-toast-hybrid#25]
"react": "17.0.1",
    "react-native": "0.64.2",
    "react-native-toast-hybrid": "^2.4.4",

![image](https://user-images.githubusercontent.com/20126939/136321974-dcfdc562-8342-4644-8fd6-b5d1fbe3ab78.png)

**Comment by baiachen** [comment]
两个库冲突了吗？

**Comment by listenzz** [comment]
是的，冲突了。

**Comment by listenzz** [comment]
你稍等，我改个名字就好
