### ISSUE TITLE
显示 Toast 时，点击操作无反应

### ISSUE THREAD

**Issue by xiaobo1234** [listenzz/react-native-toast-hybrid#27]
如题，在 Toast 显示时，页面任何点击操作都没有响应。并且，Android 侧滑退出页面会直接导致 Toast 消失。

所以，这个 Toast 是在当前页面之上 push 了一个只有 Toast 的新页面吗？

**Comment by listenzz** [comment]
> 在 Toast 显示时，页面任何点击操作都没有响应
这是正常设置

> Android 侧滑退出页面会直接导致 Toast 消失

`useToast` 和当前页面绑定，当页面消失，toast 也会消失

如果不希望页面消失，toast 也跟着消失，可以使用 `Toast#text` 这类静态方法

toast 不是 push 了一个新页面，而是在 window 添加了一个顶层 view，盖住了底下所有页面。

**Comment by xiaobo1234** [comment]
> 

好的，谢谢
